apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-scripts
data:
  10-create_user.sh: |
    #!/bin/bash
    set -e

    echo "Creating database role: keycloak"
    psql <<-EOSQL
    CREATE USER keycloak WITH CREATEDB PASSWORD 'keycloak';
    EOSQL

    echo "Creating database role: data_server"
    psql <<-EOSQL
    CREATE USER data_server WITH CREATEDB PASSWORD 'data_server';
    EOSQL
  20-create_db.sh: |
    #!/bin/bash
    set -e

    echo "Creating database: keycloak"
    psql <<EOSQL
    CREATE DATABASE keycloak OWNER keycloak;
    EOSQL

    echo "Creating database: data_server"
    psql <<EOSQL
    CREATE DATABASE data_server OWNER data_server;
    EOSQL

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: infra
  name: postgres
spec:
  selector:
    matchLabels:
      app: infra
      name: postgres
  template:
    metadata:
      labels:
        app: infra
        name: postgres
    spec:
      containers:
        - env:
            - name: POSTGRESQL_ADMIN_PASSWORD
              value: db_admin
          image: "centos/postgresql-12-centos7:20200703-6213611"
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 5432
            timeoutSeconds: 1
          name: postgres
          ports:
            - containerPort: 5432
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 5432
            timeoutSeconds: 1
          resources:
              limits:
                memory: 600Mi
              requests:
                cpu: 50m
                memory: 600Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /var/lib/pgsql/data
              name: postgres-data
            - mountPath: /usr/share/container-scripts/postgresql/start/10-create_user.sh
              name: init-scripts
              subPath: 10-create_user.sh
            - mountPath: /usr/share/container-scripts/postgresql/start/20-create_db.sh
              name: init-scripts
              subPath: 20-create_db.sh
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: postgres-data
          #persistentVolumeClaim:
           # claimName: postgres
          
          emptyDir: {}
          
        - configMap:
            defaultMode: 420
            name: postgres-init-scripts
          name: init-scripts
  
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: infra
  name: postgres
spec:
  ports:
    - name: postgres
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    app: infra
    name: postgres
  sessionAffinity: None
  type: ClusterIP
