
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: dbos
  name: dbos-documentation
spec:
  ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: dbos
    deploymentconfig: dbos-documentation
  sessionAffinity: None
  type: ClusterIP
