
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dbgene
  name: execution-service
spec:
  selector:
    matchLabels:
      app: dbgene
      deploymentconfig: execution-service
  template:
    metadata:
      labels:
        app: dbgene
        deploymentconfig: execution-service
    spec:
      containers:
        - env:
            - name: JAVA_TOOL_OPTIONS
              #value: {{ .Values.executionService.javaToolOptions }}
            - name: SPRING_RABBITMQ_HOST
              value: rabbitmq
            - name: SPRING_DATA_MONGODB_HOST
              value: mongo
            - name: SPRING_DATA_MONGODB_PORT
              value: '27017'
            - name: SERVICES_DBOSMASTER_HOST
              value: dbos-master
            - name: SERVICES_DBOSMASTER_PORT
              value: '8080'
            - name: SERVICES_EXECUTION_HOST
              value: execution-service
            - name: SERVICES_EXECUTION_PORT
              value: '8080'
            - name: SERVICES_WEB_HOST
              value: web
            - name: SERVICES_WEB_PORT
              value: '8080'
            - name: SERVICES_BACKEND_HOST
              value: backend-service
            - name: SERVICES_BACKEND_PORT
              value: '8080'
            - name: SERVICES_GATEWAY_HOST
              value: gateway-service
            - name: SERVICES_GATEWAY_PORT
              value: '8080'
            - name: SERVICES_SCENARIO_HOST
              value: scenario-service
            - name: SERVICES_SCENARIO_PORT
              value: '8080'
            - name: SERVICES_DATA_HOST
              value: data-service
            - name: SERVICES_DATA_PORT
              value: '8080'
            - name: WEBSOCKET_ALLOWEDORIGIN
              #value: https://{{ .Release.Namespace }}.{{ .Values.global.host }}
            - name: KEYCLOAK_AUTH_SERVER_URL
              value: http://keycloak:8080/auth
          image: quay.io/afcatano/knapsack-execution-service:v1.0.0
          imagePullPolicy: Always
          name: execution-service
          resources:
            limits:
              memory: 500Mi
            requests:
              cpu: 50m
              memory: 500Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
     # imagePullSecrets:
     # - name: dbgene-demos-registry.decisionbrain.cloud
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: dbgene
  name: execution-service
spec:
  ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: dbgene
    deploymentconfig: execution-service
  sessionAffinity: None
  type: ClusterIP
